apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: nodered
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodered
  name: nr-deploy
  namespace: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nr-sshd
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nr-sshd
    spec:
      containers:
      - name: nr-pod
        image: nodered/node-red
        ports:
        - containerPort: 1880
          name: nr-sshd-http
---
apiVersion: v1
kind: Service
metadata:
  name: nr-service
  namespace: nodered
spec:
  type: NodePort
  ports:
    - name: http
      port: 1880
      nodePort: 31880
      targetPort: nr-sshd-http
  selector:
    app: nr-sshd
